### ISSUE TITLE
Kilosort Sorting Flat "Clusters"

### ISSUE THREAD

**Issue by djsoper** [MouseLand/Kilosort#301] opened 2021-01-05 22:22 UTC
Hi,

I am having trouble using Kilosort2.5 to sort a Neuropixel recording which is approximately 10 minutes long. It will run through the sorting, but the Phy results leave me confused. Most of the clusters are nothing. They aren't noise or artifacts, they are just calm nothingness. Here is an example of one of the hundreds of "calm" units:
![DBS05PHYExample](https://user-images.githubusercontent.com/44448586/103705917-e1a11700-4f79-11eb-8250-a50645c37503.PNG)

The strange thing to me is that the supposed amplitude listed for this is 108.53. I wouldn't care about those arbitrary units so much if the things that actually looked like units weren't so close in amplitude. one of the very few examples of potential units I got from this recording is here, and the amplitude is just shy of 150:
![DBS05Chan141Unit](https://user-images.githubusercontent.com/44448586/103706069-317fde00-4f7a-11eb-9eeb-4d1b738f2d8b.PNG)

I'm very confused about this. Are the amplitudes relative/arbitrary for each cluster? Also, why are there so many (~300) clusters that are nothingness when it can clearly sort unit-like events. I'm very lost on this. Can you please help? I haven't changed the config file from its default(though I have tried changing some things around to no avail). Let me know if you want any more info.

Thanks,
Dan

**Comment by sachira-denagamage** [comment] 2021-01-07 14:06
I had been having a similar issue as well and tried what another user [mentioned](https://github.com/MouseLand/Kilosort/issues/297) where they changed params.py to look at the raw binary instead of the drift corrected version. I think there is some issue with the drift corrected version being read into phy.

**Comment by marius10p** [comment] 2021-01-31 19:06
This appears to indeed be related to the drift-corrected binary file being weird. Were you setting ops.trange(1) to be larger than 0? I think this was a problem before, should be fixed now.  Can you please try Kilosort3 and let me know if it's still an issue?

**Comment by rivlinoa** [comment] 2021-02-04 13:21
I am having the same issue with Kilosort3, all units from lowest amplitude to highest are flat nothing... I used default settings on Neuropixels1.0 data.

**Comment by marius10p** [comment] 2021-02-04 13:31
I can't replicate this problem. Do you have ops.trange = [0 Inf], like the default? How many connected/disconnected channels do you have?

**Comment by rivlinoa** [comment] 2021-02-04 13:45
I have ops.trange =  [0 Inf],
and all the channels in the 1.0 probe are connected (384), ops.NchanTOT = 385
It happened in 2 ut of 3 files I have managed to analyze.

thanks!!!

**Comment by marius10p** [comment] 2021-02-04 13:47
If the 3rd one was good, can you tell what was different about it? Can you cut a very small section of your file (first 10sec), replicate the problem, and send it via dropbox or google drive? Thanks,

**Comment by rivlinoa** [comment] 2021-02-04 13:54
There is nothing different (that I know of) with the successful file...
sure, I can send you a segment of one of the faulty files... where to send it to?

**Comment by marius10p** [comment] 2021-02-04 14:06
if you don't want to drop it here, please find my email address on the Cellpose paper.

**Comment by rivlinoa** [comment] 2021-02-04 15:31
So in the first 10 sec of the file everything seems to be working fine. I will have to figure out when is it happening and come up with a reproducable example. 
just a note that could give a hint in the meantime : when I load  kilosort3 results of the full file into phy (and see flat units) I get this warning :

 There are 11652178/11668546 spikes after the end of the recording.[0m

**Comment by marius10p** [comment] 2021-02-06 23:00
No worries. I think this problem is fixed now, @djsoper feel free to reopen otherwise.

**Closed by marius10p** 2021-02-06 23:00 UTC
