### ISSUE TITLE
Kilosort4 running very slow 

### ISSUE THREAD

**Issue by claudio1212** [MouseLand/Kilosort#655] opened 2024-04-03 14:39 UTC
I'm trying to use the new version of kilosort from spikeinterface and also from the "original" GUI, applying the sorting procedure to data recorded from a 32 channel floating microeletrode array, in which the contacts are spaced 400 um each (both orizontally and vertically). Spikeinterface considers my channel map as a single shank, so I did not try the "stacking" method that was proposed because I thought it was not necessary here. The GPU I'm using is NVIDIA GeForce RTX 3060.

 Using the default parameters the sorter returned an error, saying it did not find any spikes. So, after reading almost all the issues in this site, i tried changing some parameters such as dminx and dmin, min_template_size, nearest_templates and nearest_Chans. Right now, I tried with dminx and dmin=400 or 800, min_template_size=30,50,100, nearest_templates and chans =1,10 or 32 and default thresholds. In almost all these cases, I get a very large number of spikes after the first "extraction run", which then leads to a very slow clustering (I did not have the time to check how much it took to finish but it was very long). Only if I use "32" as nearest templates and chans I start to get a faster run, smaller number of extracted spikes which in turn lead to a very small number of units, especially "good" units. I'd like to know if maybe I'm using the parameters wrong or if there are other problems.

**Comment by jacobpennington** [comment] 2024-04-03 15:05
@claudio1212  I would recommend you try stacking the contacts similar to what we've suggested for multi-shank probes. The issue isn't whether it's one shank or multiple shanks per se, it's the spacing of the contacts (and yours are spaced very far apart just like if they were from separate shanks). This makes it difficult to get the templates to line up right with the probe contacts even if you're choosing a reasonable value for `dminx`. I'm hoping to push a fix for this today, but in the meantime stacking the contacts seems to be the best solution.

So, if your contacts are all 400um apart (or more), I would just make a probe with {'xc': np.ones(32), 'yc': np.arange(32)*400}. Then set `dmin = 800` so that templates are only placed exactly on the contacts. The value of `dminx` doesn't matter if all the x-positions are the same. Then set `nearest_templates` and `nearest_chans` to 1, since there won't be any neighboring channels or templates within a reasonable distance. You should also change `nblocks` to 0, since your probe will not be able to get good estimates for drift correction.

If that doesn't work, or if you don't want to mess with temporary work-arounds, I'd recommend waiting a couple days and then trying the new update.

**Comment by claudio1212** [comment] 2024-04-04 08:23
Thank you so much, now is seems to work very fine in terms of timing and units found! I will also wait for the update to try that as well.

**Closed** 2024-04-10 15:26 UTC
