### ISSUE TITLE
matlab crashing after merges

### ISSUE THREAD

**Issue by markagrios** [MouseLand/Kilosort#147] opened 2019-12-02 16:39 UTC
Hello! I'm trying to use Kilosort2 and after I load my binary file, it seems to get process everything up until is does tries to split clusters. After the merging step, Matlab throws an error and crashes but there is no erorr message on the kilosort GUI. Here is the full matlab output and the kilosort gui. Thank you!!

`Time   0s. Determining good channels.. 
found 130031 threshold crossings in 201.17 seconds of data 
found 0 bad channels 
Time  49s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening filters computed. 
Time  49s. Loading raw data and applying filters... 
Time 109s. Finished preprocessing 92 batches. 
Obtained 7 PC waveforms in 0.57 seconds 
time 0.76, pre clustered 1 / 92 batches 
time 0.16, compared 1 / 92 batches 
time 7.87, Re-ordered 92 batches. 
Time   9s. Optimizing templates ...
9.65 sec, 1 / 186 batches, 42 units, nspks: 9.8909, mu: 12.3727, nst0: 162, merges: 0.0000, 0.0000 
memorized middle timepoint 
24.60 sec, 101 / 186 batches, 410 units, nspks: 1368.5645, mu: 20.5477, nst0: 1778, merges: 100.3770, 0.0000 
reverted back to middle timepoint 
Elapsed time is 34.455012 seconds.
ntot =
      212178
Finished compressing time-varying templates 
initialized spike counts
merged 213 into 225 
merged 192 into 185 
merged 211 into 210 
merged 107 into 116 
merged 220 into 215 
merged 230 into 227 
merged 169 into 167 
merged 249 into 258 
merged 226 into 210 
merged 254 into 258 
merged 7 into 5 
merged 9 into 13 
merged 253 into 258 
merged 212 into 210 
merged 5 into 13 
merged 14 into 13 
Found 0 splits, checked 1/410 clusters, nccg 0`

![kserror](https://user-images.githubusercontent.com/6403483/69977182-f1853680-14ef-11ea-82c9-2beb26d304a0.PNG)

**Comment by marius10p** [comment] 2019-12-04 14:41
The output looks normal. What is going on with the bottom channels in your figure, are they just really negative values? Did you check the whitened data in the GUI, does it look normal? Are there NaNs or Infs in your data for whatever reason?

**Comment by markagrios** [comment] 2019-12-04 20:03
Everything looks normal to me, and since this attempt I've been removing the bad channels (black) and the problem is still here. However, I've figured out that the error only occurs when the time range surrounds a certain value but works totally fine everywhere else. I've looked at the traces at the problem time point but can't seem to find anything there, just that it fails when the time range contains the point 1837.3. Still confused but I'm making progress on finding out what's wrong

**Comment by markagrios** [comment] 2019-12-05 14:37
Still looking around, and I've determined that our optogenetic stimulating laser is causing creating some artifact that Kilosort2 gets stuck on, but I'm confused as to why it can make it through all the steps but fails at the splitting step? Shouldn't kilosort2 get rid of this in the whitening step? if not, how do I remove this artifact so matlab doesn't crash? thanks!! :D

![badpoint](https://user-images.githubusercontent.com/6403483/70244607-5338e100-173a-11ea-8c77-eda8a0887f27.PNG)

**Comment by nsteinme** [comment] 2019-12-05 15:32
You can see whether whitening has affected it by pressing "2" in the gui
(click "controls" for more details).

**Comment by markagrios** [comment] 2019-12-05 15:45
ok! the filtering didn't seem to get rid of it, is there some parameter I can change to make this go away? sorry, I'm still very new to kilosort/spike sorting in general

![filtered_badpoint](https://user-images.githubusercontent.com/6403483/70250574-b2e7ba00-1743-11ea-8d49-77671847accf.PNG)

**Comment by markagrios** [comment] 2019-12-05 16:37
the program fails specifically on splits 1/2, and from the documentation "The first pass is initialized with the top principal component of the cluster". Maybe the artifact from the laser is so far away in the principal component space that initializing the first pass of splits with this ruins the rest of the clusters?

**Comment by grahamfindlay** [comment] 2020-12-23 02:38
Is it possible that this issue is a duplicate of #199 ? If so, check there for the solution @markagrios .

**Closed** 2024-02-29 13:02 UTC
